INSERT INTO PERSON (ID, NAME, PHONE_NUMBER) VALUES (1, 'Gleb', '12345');
INSERT INTO CONTACT (ID, NAME, PHONE_NUMBER, PERSON_ID) VALUES (2, 'Valera', '2345', 1);
INSERT INTO CONTACT (ID, NAME, PHONE_NUMBER, PERSON_ID) VALUES (3, 'Florov', '3456', 1);
INSERT INTO CONTACT (ID, NAME, PHONE_NUMBER, PERSON_ID) VALUES (4, 'Nastya', '4567', 1);